import SwiftUI

struct ContentView: View {
    var body: some View {
        ZStack {
            // 背景
            Color.gray
                .opacity(0.5)
                .ignoresSafeArea()
            // 面具中上
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskTopLight))
                .frame(width: 270, height: 270)
                .rotationEffect(.degrees(-45))
                .offset(x:-96, y: -200)
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskTopLight))
                .frame(width: 270, height: 270)
                .rotationEffect(.degrees(-45))
                .offset(x:-96, y: -200)
                .scaleEffect(x: -1, y: 1)
            // 面具右上1
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskTopLight))
                .frame(width: 270, height: 270)
                .rotationEffect(.degrees(160))
                .offset(x:150, y: -135)
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskTopLight))
                .frame(width: 270, height: 270)
                .rotationEffect(.degrees(-20))
                .offset(x:-24, y: -215)
            // 面具右上2
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskTopLight))
                .frame(width: 270, height: 270)
                .rotationEffect(.degrees(200))
                .offset(x:130, y: -30)
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskTopLight))
                .frame(width: 270, height: 270)
                .rotationEffect(.degrees(20))
                .offset(x:50, y: -204)
            // 面具左上1
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskTopLight))
                .frame(width: 270, height: 270)
                .rotationEffect(.degrees(160))
                .offset(x:150, y: -135)
                .scaleEffect(x: -1, y: 1)
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskTopLight))
                .frame(width: 270, height: 270)
                .rotationEffect(.degrees(-20))
                .offset(x:-24, y: -215)
                .scaleEffect(x: -1, y: 1)
            // 面具左上2
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskTopLight))
                .frame(width: 270, height: 270)
                .rotationEffect(.degrees(200))
                .offset(x:130, y: -30)
                .scaleEffect(x: -1, y: 1)
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskTopLight))
                .frame(width: 270, height: 270)
                .rotationEffect(.degrees(20))
                .offset(x:50, y: -204)
                .scaleEffect(x: -1, y: 1)
            // 面具右下1
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskDown))
                .frame(width: 297, height: 297)
                .rotationEffect(.degrees(200))
                .offset(x:145, y: 50)
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskDown))
                .frame(width: 297, height: 297)
                .rotationEffect(.degrees(20))
                .offset(x:56, y: -141)
            // 面具右下2
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskDown))
                .frame(width: 162, height: 162)
                .rotationEffect(.degrees(230))
                .scaleEffect(x: 1.1, y: 1.1)
                .offset(x:90, y: 80)
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskDown))
                .frame(width: 162, height: 162)
                .rotationEffect(.degrees(50))
                .scaleEffect(x: 1.1, y: 1.1)
                .offset(x:101, y: -46)
            // 面具右下3
            Rectangle()
                .fill(Color(.maskDown))
                .frame(width: 100, height: 100)
                .rotationEffect(.degrees(20))
                .offset(x:89, y: 50)
                .mask {
                    Circle()
                        .trim(from: 0.0, to: 0.25)
                        .frame(width: 162, height: 162)
                        .rotationEffect(.degrees(260))
                        .scaleEffect(x: 1.1, y: 1.1)
                        .offset(x:15, y: 185)
                    Circle()
                        .trim(from: 0.0, to: 0.25)
                        .frame(width: 162, height: 162)
                        .rotationEffect(.degrees(80))
                        .scaleEffect(x: 1.1, y: 1.1)
                        .offset(x:88, y: -88)
                }
            // 面具左下1
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskDown))
                .frame(width: 297, height: 297)
                .rotationEffect(.degrees(200))
                .offset(x:145, y: 50)
                .scaleEffect(x: -1, y: 1)
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskDown))
                .frame(width: 297, height: 297)
                .rotationEffect(.degrees(20))
                .offset(x:56, y: -141)
                .scaleEffect(x: -1, y: 1)
            // 面具左下2
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskDown))
                .frame(width: 162, height: 162)
                .rotationEffect(.degrees(230))
                .scaleEffect(x: 1.1, y: 1.1)
                .offset(x:90, y: 80)
                .scaleEffect(x: -1, y: 1)
            Circle()
                .trim(from: 0.0, to: 0.25)
                .fill(Color(.maskDown))
                .frame(width: 162, height: 162)
                .rotationEffect(.degrees(50))
                .scaleEffect(x: 1.1, y: 1.1)
                .offset(x:101, y: -46)
                .scaleEffect(x: -1, y: 1)
            // 面具左下3
            Rectangle()
                .fill(Color(.maskDown))
                .frame(width: 100, height: 100)
                .rotationEffect(.degrees(20))
                .offset(x:89, y: 50)
                .scaleEffect(x: -1, y: 1)
                .mask {
                    Circle()
                        .trim(from: 0.0, to: 0.25)
                        .frame(width: 162, height: 162)
                        .rotationEffect(.degrees(260))
                        .scaleEffect(x: 1.1, y: 1.1)
                        .offset(x:15, y: 185)
                        .scaleEffect(x: -1, y: 1)
                    Circle()
                        .trim(from: 0.0, to: 0.25)
                        .frame(width: 162, height: 162)
                        .rotationEffect(.degrees(80))
                        .scaleEffect(x: 1.1, y: 1.1)
                        .offset(x:88, y: -88)
                        .scaleEffect(x: -1, y: 1)
                }
            // 面具臉部上方
            Rectangle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.black))
                .frame(width: 130, height: 130)
                .scaleEffect(x: 0.25, y: 1)
                .offset(x: -60, y: -55)
            Rectangle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.black))
                .frame(width: 130, height: 130)
                .scaleEffect(x: 0.25, y: 1)
                .offset(x: -60, y: -55)
                .scaleEffect(x: -1, y: 1)
            Rectangle()
                .fill(Color(.black))
                .frame(width: 90, height: 130)
                .offset(x: 0, y: -55)
            Rectangle()
                .fill(Color(.maskTopDark))
                .frame(width: 353, height: 130)
                .offset(x: 0, y: -91)
                .mask {
                    Circle()
                        .trim(from: 0.0, to: 0.5)
                        .stroke(lineWidth: 4)
                        .frame(width: 353, height: 353)
                        .scaleEffect(x: 1, y: 0.3)
                        .offset(x: 0, y: -163)
                }
            Rectangle()
                .fill(Color(.maskTopLight))
                .frame(width: 353, height: 130)
                .offset(x: 0, y: -91)
                .mask {
                    Circle()
                        .trim(from: 0.0, to: 0.5)
                        .frame(width: 353, height: 353)
                        .scaleEffect(x: 1, y: 0.3)
                        .offset(x: 0, y: -164)
                }
            // 眼睛
            Rectangle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 40, height: 40)
                .rotationEffect(Angle(degrees: -45))
                .scaleEffect(x: 0.3, y: 1)
                .rotationEffect(Angle(degrees: -30))
                .offset(x: -51, y: -85)
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 40, height: 40)
                .rotationEffect(Angle(degrees: 180))
                .offset(x: -38, y: -80)
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.black))
                .frame(width: 40, height: 40)
                .rotationEffect(Angle(degrees: 180))
                .offset(x: -38, y: -71)
            Rectangle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 40, height: 40)
                .rotationEffect(Angle(degrees: -45))
                .scaleEffect(x: 0.3, y: 1)
                .rotationEffect(Angle(degrees: -30))
                .offset(x: -51, y: -85)
                .scaleEffect(x: -1, y: 1)
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 40, height: 40)
                .rotationEffect(Angle(degrees: 180))
                .offset(x: -38, y: -80)
                .scaleEffect(x: -1, y: 1)
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.black))
                .frame(width: 40, height: 40)
                .rotationEffect(Angle(degrees: 180))
                .offset(x: -38, y: -71)
                .scaleEffect(x: -1, y: 1)
            // 面具臉部下方
            Rectangle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.maskFace))
                .frame(width: 30, height: 30)
                .rotationEffect(Angle(degrees: -45))
                .scaleEffect(x: 0.6, y: 1)
                .offset(x: 0, y: -75)
            Rectangle()
                .fill(Color(.maskFace))
                .frame(width: 26, height: 40)
                .offset(x: 0, y: -55)
            Rectangle()
                .fill(Color(.maskFace))
                .frame(width: 150, height: 100)
                .offset(x: 0, y: -37)
                .mask {
                    ZStack {
                        Circle()
                            .trim(from: 0.0, to: 0.5)
                            .frame(width: 100, height: 100)
                            .rotationEffect(Angle(degrees: -104))
                            .offset(x: -57, y: -25)
                        Circle()
                            .trim(from: 0.0, to: 0.5)
                            .frame(width: 100, height: 100)
                            .rotationEffect(Angle(degrees: -104))
                            .offset(x: -57, y: -25)
                            .scaleEffect(x: -1, y: 1)
                        Rectangle()
                            .frame(width: 80, height: 60)
                            .offset(x: 0, y: -5)
                    }
                }
            // 面具陰影
            Circle()
                .trim(from: 0.0, to: 0.2)
                .fill(Color(.maskFaceShadow))
                .frame(width: 100, height: 100)
                .rotationEffect(Angle(degrees: 207))
                .offset(x: -6, y: 44)
            Rectangle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.maskFaceShadow))
                .frame(width: 75, height: 75)
                .rotationEffect(Angle(degrees: -45))
                .scaleEffect(x: 0.15, y: 1)
                .rotationEffect(Angle(degrees: -108))
                .offset(x: 2, y: 2)
            Circle()
                .trim(from: 0.0, to: 0.2)
                .fill(Color(.maskFaceShadow))
                .frame(width: 100, height: 100)
                .rotationEffect(Angle(degrees: 207))
                .offset(x: -6, y: 44)
                .scaleEffect(x: -1, y: 1)
            Rectangle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.maskFaceShadow))
                .frame(width: 75, height: 75)
                .rotationEffect(Angle(degrees: -45))
                .scaleEffect(x: 0.15, y: 1)
                .rotationEffect(Angle(degrees: -108))
                .offset(x: 2, y: 2)
                .scaleEffect(x: -1, y: 1)
            Rectangle()
                .fill(Color(.maskFaceShadow))
                .frame(width: 75, height: 5)
                .offset(x: 0, y: 10)
            Circle()
                .fill(Color(.maskFaceShadow))
                .frame(width: 100, height: 150)
                .offset(x: 0, y: 30)
                .mask {
                    ZStack {
                        Rectangle()
                            .trim(from: 0.0, to: 0.5)
                            .fill(Color(.maskFaceShadow))
                            .frame(width: 60, height: 60)
                            .rotationEffect(Angle(degrees: -45))
                            .scaleEffect(x: 0.2, y: 1)
                            .rotationEffect(Angle(degrees: 210))
                            .offset(x: 50, y: 30)
                        Rectangle()
                            .trim(from: 0.0, to: 0.5)
                            .fill(Color(.maskFaceShadow))
                            .frame(width: 60, height: 60)
                            .rotationEffect(Angle(degrees: -45))
                            .scaleEffect(x: 0.2, y: 1)
                            .rotationEffect(Angle(degrees: -30))
                            .offset(x: 50, y: 35)
                        Rectangle()
                            .trim(from: 0.0, to: 0.5)
                            .fill(Color(.maskFaceShadow))
                            .frame(width: 60, height: 60)
                            .rotationEffect(Angle(degrees: -45))
                            .scaleEffect(x: 0.2, y: 1)
                            .rotationEffect(Angle(degrees: 210))
                            .offset(x: 50, y: 30)
                            .scaleEffect(x: -1, y: 1)
                        Rectangle()
                            .trim(from: 0.0, to: 0.5)
                            .fill(Color(.maskFaceShadow))
                            .frame(width: 60, height: 60)
                            .rotationEffect(Angle(degrees: -45))
                            .scaleEffect(x: 0.2, y: 1)
                            .rotationEffect(Angle(degrees: -30))
                            .offset(x: 50, y: 35)
                            .scaleEffect(x: -1, y: 1)
                    }
                }
            // 嘴部
            Rectangle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.black))
                .frame(width: 70, height: 70)
                .rotationEffect(Angle(degrees: -45))
                .scaleEffect(x: 0.3, y: 1)
                .rotationEffect(Angle(degrees: -35))
                .offset(x: -30, y: -10)
            Rectangle()
                .fill(Color(.black))
                .frame(width: 22, height: 50)
                .rotationEffect(Angle(degrees: -60))
                .offset(x: -15, y: -30)
            Rectangle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.black))
                .frame(width: 70, height: 70)
                .rotationEffect(Angle(degrees: -45))
                .scaleEffect(x: 0.3, y: 1)
                .rotationEffect(Angle(degrees: -35))
                .offset(x: -30, y: -10)
                .scaleEffect(x: -1, y: 1)
            Rectangle()
                .fill(Color(.black))
                .frame(width: 22, height: 50)
                .rotationEffect(Angle(degrees: -60))
                .offset(x: -15, y: -30)
                .scaleEffect(x: -1, y: 1)
            // 紋路中上
            Rectangle()
                .fill(Color(.maskTopDark))
                .frame(width: 3, height: 50)
                .offset(x:0, y: -240)
            // 紋路中下
            Rectangle()
                .fill(Color(.maskTopDark))
                .frame(width: 55, height: 50)
                .offset(x:0, y: -120)
                .mask {
                    ZStack {
                        Circle()
                            .trim(from: 0.0, to: 0.5)
                            .stroke(lineWidth: 3)
                            .frame(width: 50, height: 50)
                            .rotationEffect(Angle(degrees: -90))
                            .offset(x:0, y: -136)
                        Circle()
                            .trim(from: 0.0, to: 0.5)
                            .stroke(lineWidth: 3)
                            .frame(width: 50, height: 50)
                            .rotationEffect(Angle(degrees: -90))
                            .offset(x:0, y: -136)
                            .scaleEffect(x: -1, y: 1)
                    }
                    
                }
            // 紋路右上1
            Rectangle()
                .fill(Color(.maskTopDark))
                .frame(width: 50, height: 50)
                .offset(x:15, y: -208)
                .mask {
                    Circle()
                        .stroke(lineWidth: 5)
                        .frame(width: 35, height: 35)
                        .scaleEffect(x: 0.6, y: 1)
                        .rotationEffect(Angle(degrees: 20))
                        .offset(x:43, y: -197)
                }
            // 紋路右上2
            Rectangle()
                .fill(Color(.maskTopDark))
                .frame(width: 35, height: 40)
                .offset(x:50, y: -170)
                .mask {
                    Circle()
                        .stroke(lineWidth: 3)
                        .frame(width: 35, height: 35)
                        .offset(x:44, y: -170)
                }
            // 紋路右上3
            Rectangle()
                .fill(Color(.maskTopDark))
                .frame(width: 50, height: 50)
                .offset(x:55, y: -130)
                .mask {
                    Circle()
                        .stroke(lineWidth: 3)
                        .frame(width: 70, height: 70)
                        .offset(x: 0, y: -145)
                }
            // 紋路右中1
            Rectangle()
                .fill(Color(.maskTopDark))
                .frame(width: 35, height: 27)
                .offset(x:81, y: -150)
                .mask {
                    Circle()
                        .stroke(lineWidth: 5)
                        .frame(width: 50, height: 50)
                        .scaleEffect(x: 1, y: 0.6)
                        .rotationEffect(Angle(degrees: -25))
                        .offset(x:86, y: -143)
                }
            // 紋路右中2
            Rectangle()
                .fill(Color(.maskTopDark))
                .frame(width: 45, height: 55)
                .rotationEffect(Angle(degrees: 80))
                .offset(x:54, y: -123)
                .mask {
                    Circle()
                        .stroke(lineWidth: 3)
                        .frame(width: 40, height: 40)
                        .offset(x:44, y: -143)
                    
                }
            // 紋路左上1
            Rectangle()
                .fill(Color(.maskTopDark))
                .frame(width: 50, height: 50)
                .offset(x:15, y: -208)
                .mask {
                    Circle()
                        .stroke(lineWidth: 5)
                        .frame(width: 35, height: 35)
                        .scaleEffect(x: 0.6, y: 1)
                        .rotationEffect(Angle(degrees: 20))
                        .offset(x:43, y: -197)
                }
                .scaleEffect(x: -1, y: 1)
            // 紋路左上2
            Rectangle()
                .fill(Color(.maskTopDark))
                .frame(width: 35, height: 40)
                .offset(x:50, y: -170)
                .mask {
                    Circle()
                        .stroke(lineWidth: 3)
                        .frame(width: 35, height: 35)
                        .offset(x:44, y: -170)
                }
                .scaleEffect(x: -1, y: 1)
            // 紋路左上3
            Rectangle()
                .fill(Color(.maskTopDark))
                .frame(width: 50, height: 50)
                .offset(x:55, y: -130)
                .mask {
                    Circle()
                        .stroke(lineWidth: 3)
                        .frame(width: 70, height: 70)
                        .offset(x: 0, y: -145)
                }
                .scaleEffect(x: -1, y: 1)
            // 紋路左中1
            Rectangle()
                .fill(Color(.maskTopDark))
                .frame(width: 35, height: 27)
                .offset(x:81, y: -150)
                .mask {
                    Circle()
                        .stroke(lineWidth: 5)
                        .frame(width: 50, height: 50)
                        .scaleEffect(x: 1, y: 0.6)
                        .rotationEffect(Angle(degrees: -25))
                        .offset(x:86, y: -143)
                }
                .scaleEffect(x: -1, y: 1)
            // 紋路左中2
            Rectangle()
                .fill(Color(.maskTopDark))
                .frame(width: 45, height: 55)
                .rotationEffect(Angle(degrees: 80))
                .offset(x:54, y: -123)
                .mask {
                    Circle()
                        .stroke(lineWidth: 3)
                        .frame(width: 40, height: 40)
                        .offset(x:44, y: -143)
                    
                }
                .scaleEffect(x: -1, y: 1)
            // 太晶中央
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 70, height: 70)
                .rotationEffect(Angle(degrees: -90))
                .scaleEffect(x: 0.3, y: 1)
                .offset(x: 0, y: -170)
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 70, height: 70)
                .rotationEffect(Angle(degrees: -90))
                .scaleEffect(x: 0.3, y: 1)
                .offset(x: 0, y: -170)
                .scaleEffect(x: -1, y: 1)
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 70, height: 70)
                .rotationEffect(Angle(degrees: -180))
                .scaleEffect(x: 0.7, y: 0.3)
                .offset(x: 0, y: -170)
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 70, height: 70)
                .scaleEffect(x: 0.7, y: 0.3)
                .offset(x: 0, y: -170)
            // 太晶右下1
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 90, height: 90)
                .scaleEffect(x: 1, y: 0.2)
                .rotationEffect(Angle(degrees: -25))
                .offset(x: 120, y: -55)
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 90, height: 90)
                .scaleEffect(x: 1, y: 0.2)
                .rotationEffect(Angle(degrees: 155))
                .offset(x: 120, y: -55)
            // 太晶右下2
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 60, height: 60)
                .scaleEffect(x: 1, y: 0.2)
                .rotationEffect(Angle(degrees: 10))
                .offset(x: 100, y: 15)
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 60, height: 60)
                .scaleEffect(x: 1, y: 0.2)
                .rotationEffect(Angle(degrees: 190))
                .offset(x: 100, y: 15)
            // 太晶右下3
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 40, height: 40)
                .scaleEffect(x: 1, y: 0.2)
                .rotationEffect(Angle(degrees: 40))
                .offset(x: 68, y: 60)
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 40, height: 40)
                .scaleEffect(x: 1, y: 0.2)
                .rotationEffect(Angle(degrees: 220))
                .offset(x: 68, y: 60)
            // 太晶左下1
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 90, height: 90)
                .scaleEffect(x: 1, y: 0.2)
                .rotationEffect(Angle(degrees: -25))
                .offset(x: 120, y: -55)
                .scaleEffect(x: -1, y: 1)
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 90, height: 90)
                .scaleEffect(x: 1, y: 0.2)
                .rotationEffect(Angle(degrees: 155))
                .offset(x: 120, y: -55)
                .scaleEffect(x: -1, y: 1)
            // 太晶左下2
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 60, height: 60)
                .scaleEffect(x: 1, y: 0.2)
                .rotationEffect(Angle(degrees: 10))
                .offset(x: 100, y: 15)
                .scaleEffect(x: -1, y: 1)
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 60, height: 60)
                .scaleEffect(x: 1, y: 0.2)
                .rotationEffect(Angle(degrees: 190))
                .offset(x: 100, y: 15)
                .scaleEffect(x: -1, y: 1)
            // 太晶左下3
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 40, height: 40)
                .scaleEffect(x: 1, y: 0.2)
                .rotationEffect(Angle(degrees: 40))
                .offset(x: 68, y: 60)
                .scaleEffect(x: -1, y: 1)
            Circle()
                .trim(from: 0.0, to: 0.5)
                .fill(Color(.white))
                .frame(width: 40, height: 40)
                .scaleEffect(x: 1, y: 0.2)
                .rotationEffect(Angle(degrees: 220))
                .offset(x: 68, y: 60)
                .scaleEffect(x: -1, y: 1)
        }
    }
}

#Preview {
    ContentView()
}
